version: '3.4'

services:
  sgfdevs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "${APP_HTTP_PORT:-5000}:80"
      - "${APP_HTTPS_PORT:-5001}:443"
    volumes:
      - ${USER_SECRETS_PATH}:/root/.microsoft/usersecrets:ro
      - ${ASPNET_HTTPS_PATH}:/root/.aspnet/https:ro
