version:  '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    ports:
      - '10600:10600'
    volumes:
      - .:/src
    networks:
      - sgfdevs
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.6
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - 'ACCEPT_EULA=1'
      - 'MSSQL_SA_PASSWORD=P@ssw0rd'
    ports:
      - '1433:1433'
    hostname: mssql
    volumes:
      - 'mssql-azuresql-edge-data:/var/opt/mssql'
    networks:
      - sgfdevs
volumes:
  mssql-azuresql-edge-data:

networks:
  sgfdevs:
    driver: bridge